[build]
  command = "npm run build"
  publish = "dist/zen-dojo/browser"

[[headers]]
  for = "/ngsw-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
